languageCode = "en"
languageName = "English"
weight = 1
title = "Bowen's Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[author]
name = "Hu Bowen"
image = "profile.jpeg"
headline = "Cybersecurity Student @ Ngee Ann Polytechnic"
bio = ""
links = [ { email = "mailto://contact@hubowen.dev" }, { github = "https://github.com/notbowen" }, { linkedin = "https://linkedin.com/in/hubowen" } ]
