baseURL = "https://hubowen.dev/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Hu Bowen"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    pre = "<span data-feather='home'></span>"

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
    pre = "<span data-feather='book'></span>"

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume.pdf"
    weight = 3
    pre = "<span data-feather='file-text'></span>"

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 4
    pre = "<span data-feather='tag'></span>"
    
[params]
  dateFormat = "02 January 2006"

  socialIcons = [
    {name = "github", url = "https://github.com/notbowen"},
    {name = "linkedin", url = "https://linkedin.com/in/hubowen"},
    {name = "email", url = "mailto://contact@hubowen.dev"},
  ]

  # URL for the avatar on homepage
  avatarURL = "/images/avatar.png"

  # Description to display on homepage
  description = "Cybersecurity Student @ Ngee Ann Polytechnic"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # Display "back to top" button on posts
  ShowBackToTopButton = true

  # Footer text
  footer = "Hu Bowen"

  # Custom KATEX Styling
  customHeadHTML = '''
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          throwOnError : false
        });
      });
    </script>
  '''